// import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";
import { alertAtom } from "@/lib/store/alertStore";
import { modalAtom } from "@/lib/store/modalStore";
import { AlertManager } from "@/util/hook/useAlert";
import { ModalManager } from "@/util/hook/useModal";
import "./globals.css";
import Providers from "./providers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "모아",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>{children}</Providers>
        {alertAtom && <AlertManager />}
        {modalAtom && <ModalManager />}
      </body>
    </html>
  );
}
